export type HumanPresenceErrorCode =
  | 'INVALID_HUMAN_PRESENCE_INPUT'
  | 'OWNER_NOT_FOUND'
  | 'CREDENTIAL_NOT_REGISTERED'
  | 'REGISTRATION_CHALLENGE_NOT_FOUND'
  | 'REGISTRATION_CHALLENGE_CONSUMED'
  | 'REGISTRATION_CHALLENGE_EXPIRED'
  | 'REGISTRATION_CHALLENGE_NOT_YET_VALID'
  | 'REGISTRATION_VERIFICATION_FAILED'
  | 'PLAN_AUTHENTICATION_CHALLENGE_NOT_FOUND'
  | 'PLAN_AUTHENTICATION_CHALLENGE_CONSUMED'
  | 'PLAN_AUTHENTICATION_CHALLENGE_EXPIRED'
  | 'PLAN_AUTHENTICATION_CHALLENGE_NOT_YET_VALID'
  | 'PLAN_BINDING_MISMATCH'
  | 'PLAN_AUTHENTICATION_VERIFICATION_FAILED'
  | 'CREDENTIAL_COUNTER_CONFLICT'

export class HumanPresenceError extends Error {
  readonly code: HumanPresenceErrorCode

  constructor(code: HumanPresenceErrorCode, options?: ErrorOptions) {
    super(code, options)
    this.name = 'HumanPresenceError'
    this.code = code
  }
}
